import Link from "next/link";

export default function TermsOfService() {
    return (
        <div style={{ minHeight: "100vh", background: "var(--background)", color: "var(--foreground)" }}>
            {/* Navbar */}
            <nav
                style={{
                    display: "flex",
                    alignItems: "center",
                    padding: "0 48px",
                    height: 72,
                    borderBottom: "1px solid var(--border-color)",
                    position: "sticky",
                    top: 0,
                    zIndex: 100,
                    background: "var(--background)",
                    backdropFilter: "blur(12px)",
                }}
            >
                <Link href="/" style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--muted)", textDecoration: "none", fontWeight: 500, fontSize: "0.875rem" }} className="hover:text-foreground">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <line x1="19" y1="12" x2="5" y2="12"></line>
                        <polyline points="12 19 5 12 12 5"></polyline>
                    </svg>
                    Back to Home
                </Link>
            </nav>

            <main style={{ maxWidth: 800, margin: "0 auto", padding: "60px 24px 100px" }}>
                <h1 style={{ fontSize: "2.5rem", fontWeight: 800, marginBottom: 16, letterSpacing: "-0.02em" }}>Terms of Service</h1>
                <p style={{ color: "var(--muted)", marginBottom: 48, fontSize: "1.125rem" }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>1. Acceptance of Terms</h3>
                    <p>
                        By accessing or using VoiceCV, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access our service.
                    </p>
                </section>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>2. User Accounts</h3>
                    <p>
                        You are responsible for safely maintaining the confidentiality of your account credentials. You agree to accept responsibility for all activities that occur under your account.
                    </p>
                    <p>
                        You must provide accurate and complete information when creating an account. Providing false information may result in termination of your account.
                    </p>
                </section>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>3. Acceptable Use</h3>
                    <p>
                        Our AI assistant is designed to help you build professional resumes. You agree not to use the service to:
                    </p>
                    <ul>
                        <li>Generate explicit, offensive, or harmful content.</li>
                        <li>Attempt to bypass, exploit, or reverse-engineer our AI systems.</li>
                        <li>Use the platform for any illegal or unauthorized purpose.</li>
                    </ul>
                </section>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>4. Service Availability & Output Accuracy</h3>
                    <p>
                        While we strive for high availability, we do not guarantee that the service will be uninterrupted, secure, or error-free.
                    </p>
                    <p>
                        The resumes generated by VoiceCV are created by Artificial Intelligence based on your inputs. While the AI is trained to produce professional results, <strong>you are solely responsible for reviewing and verifying the accuracy of your final CV</strong> before submitting it to any employer. We are not liable for any inaccuracies or outcomes resulting from the use of the generated documents.
                    </p>
                </section>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>5. Pricing and Payments</h3>
                    <p>
                        Creating your CV is free, but exporting or downloading the final PDF requires payment. We offer two options:
                    </p>
                    <ul>
                        <li><strong>Single CV:</strong> A one-time payment of $4.99 for a single resume download.</li>
                        <li><strong>Pro Plan:</strong> A monthly subscription of $9.99 allowing up to 10 resume downloads per month.</li>
                    </ul>
                    <p>
                        All payments are processed securely via Lemon Squeezy, our merchant of record. By completing a purchase, you also agree to Lemon Squeezy's terms and conditions.
                    </p>
                </section>

                <section style={{ marginBottom: 40 }} className="chat-markdown">
                    <h3>Contact Us</h3>
                    <p>
                        If you have any questions about these Terms, please contact us at <a href="mailto:support@voicecv.app" style={{ color: "var(--color-primary)" }}>support@voicecv.app</a>.
                    </p>
                </section>
            </main>
        </div>
    );
}
